import dotenv from 'dotenv';

dotenv.config();
const {
  NODE_ENV,
  HOST,
  PORT,
  FRONT_URL,
  DB_NAME,
  DB_USER,
  DB_HOST,
  DB_DRIVER,
  DB_PASSWORD,
  DB_PORT,
  REDIS_URL,
  USER_PASSWORD_SECRET,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN,
  JWT_SECRET_ACCESS,
  JWT_SECRET_REFRESH,
  JWT_SECRET_VERIFY,
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_USER,
  EMAIL_PASSWORD,
  EMAIL_FROM
} = process.env;

export {
  NODE_ENV,
  HOST,
  PORT,
  FRONT_URL,
  DB_NAME,
  DB_USER,
  DB_HOST,
  DB_DRIVER,
  DB_PASSWORD,
  DB_PORT,
  REDIS_URL,
  USER_PASSWORD_SECRET,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN,
  JWT_SECRET_ACCESS,
  JWT_SECRET_REFRESH,
  JWT_SECRET_VERIFY,
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_USER,
  EMAIL_PASSWORD,
  EMAIL_FROM
};
